module.exports = [
  {
      batch_id: 0
    , startDate: new Date(2011, 6, 18)
    , users: [
        'muffs'
      , 'j2labs'
      , 'artemtitoulenko'
      , 'kylewpppd'
      , 'workmajj'
    ]
  },
  {
      batch_id: 1
    , startDate: new Date(2011, 8, 29)
    , users: [
        'gone'
      , 'levberlin'
      , 'omni5cience'
      , 'ramz15'
      , 'talos'
      , 'kristiankristensen'
      , 'jyli7'
      , 'sethmurphy'
      , 'jordanorelli'
      , 'supacliny'
    ]
  },
  {
      batch_id: 2
    , startDate: new Date(2012, 1, 13)
    , users: [
        'zallarak'
      , 'antoviaque'
      , 'jab'
      , 'lchi'
      , 'cirsteve'
      , 'jconnolly'
      , 'daniellesucher'
      , 'stuntgoat'
      , 'myf'
      , 'colinmarc'
      , 'davemckenna01'
      , 'nmichalov'
      , 'brendannee'
      , 'sidnicious'
      , 'shwaydogg'
      , 'euccastro'
    ]
  },
  {
      batch_id: 3
    , startDate: new Date(2012, 6, 4)
    , users: [
  		  'shirmung'
  		, 'cavedweller'
  		, 'davekong'
  		, 'ingrid'
  		, 'S714726'
  		, 'maryrosecook'
  		, 'pepijndevos'
  		, 'oxling'
  		, 'ericfode'
  		, 'dillonforrest'
  		, 'dustingetz'
  		, 'nphoff'
  		, 'akaptur'
  		, 'jamak'
  		, 'jasonLaster'
  		, 'bev-a-tron'
  		, 'davidleibovic'
  		, 'bmacri'
  		, 'vickimo'
  		, 'niftynei'
  		, 'linse'
  		, 'dunvi'
  		, 'grstearns'
  		, 'oskarth'
  		, 'zachallaun'
  		, 'aerenchyma'
  		, 'doda'
  		, 'Sean-Der'
  		, 'lpellis'
  		, 'yaelelmatad'
  		, 'julienfantin'
  		, 'tgebru'
  		, 'marthakelly'
  		, 'smargonz'
  		, 'TreyLawrence'
  		, 'drrckln'
  		, 'govindmanian'
  		, 'dennismartensson'
  		, 'ariamoraine'
  		, 'muhtasib'
  		, 'sarenji'
  		, 'trucy'
  		, 'vu2srk'
  		, 'bramsey'
  		, 'mil'
  		, 'fiveplusone'
  		, 'jns2'
  		, 'sunahsuh'
  		, 'janewang' 
		]
  },
  {
      batch_id: 4
    , startDate: new Date(2012, 9, 1)
    , users: [
        'davidbalbert'
      , 'thomasballinger'
      , 'nicholasbs'
      , 'jollysonali'
      , 'kaizokuace'
      , 'zachallaun'
      , 'sent-hil'
      , 'svaksha'
      , 'darius'
      , 'ebeer'
      , 'jamii'
      , 'angusb'
      , 'forklady42'
      , 'rubychilds'
      , 'ciniglio'
      , 'jac300'
      , 'uctpphd'
      , 'zdexter'
      , 'lfranchi'
      , 'syntacticsugar'
      , 'cjab'
      , 'blake41'
      , 'Dwaynekj'
      , 'akaptur'
      , 'celeritas17'
      , 'margo-K'
      , 'TedLee'
      , 'becdot'
      , 'redWallaroo'
      , 'coreylynch'
      , 'myf'
      , 'ariamoraine'
      , 'pnichols104'
      , 'happy4crazy'
      , 'bigsnarfdude'
      , 'DeadDork'
      , 'stoneG'
      , 'cpetzold'
      , 'vu2srk'
      , 'kisha'
      , 'charmeleon'
      , 'trobertson'
      , 'stanistan'
      , 'jschneier'
      , 'jamesshieh'
      , 'holgersindbaek'
      , 'tks2103'
      , 'raysohn'
      , 'kenyavs'
      , 'swoopej'
      , 'oskarth'
      , 'heyhuyen'
      , 'rtunney'
      , 'kristenwidman'
      , 'mwieler'
      , 'jennazee'
    ]
  }
]